GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users
content-type: application/json

{
    "username": "top gun",
    "password": "12345"
}

###

DELETE http://localhost:5000/api/movies/favorites/760161
