GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users/auth
content-type: application/json

{
    "username": "top gun",
    "password": "12345",
    "accessToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvcCBndW4iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNjY0NjM2NDI1LCJleHAiOjE2NjQ2MzY0MzB9.pU3Xla8W1baVYK_u5FNkZ_Jzix-XB8MWxocsKjnm4a0"
}

###

DELETE http://localhost:5000/api/movies/favorites/760161
